### ISSUE TITLE
Refactor get handling of chemical formular

### ISSUE THREAD

**Issue by viktorht** [mmattano/AutoFlow-OmicsDataHandling#20]
The following lines extract the molecular formula from the fragment IDs which is unexpected behaviour and makes the reimport fail if the fragment ID does not contain a valid formula.

https://github.com/mmattano/AutoFlow-OmicsDataHandling/blob/a7b2e05ce4e8b9c5c6401a89570eeaa14ca26a90/BFAIR/mfa/INCA/INCA_reimport.py#L852-L878

The molecular formula should instead be handled through the `.more` attribute of the fragments (defined through the msdata()-function). The information can then be exported through the model-matlab object (usually called `m` in the reimport notebooks), which should contain the information in the .more attribute. An issue is that the .more attribute contains the formula for all unlabelled atoms, thus to obtain the full formula one should add the .more attribute with the .atoms attribute (that contains the labelled atoms) for each fragment.

## TODO
- [x] Make a function that imports the `fragment_formula` from the measuredFragments file and write the unlabelled atoms in the .more attribute in the matlab script.
     - [x]  Make a helper function which takes subtracts the labelled atoms from the full formula
- [ ] Make a function which extracts the full formula (.more + .atoms) from the model matlab-object
- [ ] Calculate the molar mass from the formula
- [ ] Save formula, and molar mass to the out dataframe in reimport workflow
